const MATCHES = [
  // 1ª Rodada
  { id: 'm1',  home: 'México',        homeFlag: '🇲🇽', away: 'África do Sul',  awayFlag: '🇿🇦', date: '11/06 16h', group: 'Grupo A' },
  { id: 'm2',  home: 'Coreia do Sul', homeFlag: '🇰🇷', away: 'Rep. Tcheca',    awayFlag: '🇨🇿', date: '11/06 23h', group: 'Grupo A' },
  { id: 'm3',  home: 'Canadá',        homeFlag: '🇨🇦', away: 'Itália',         awayFlag: '🇮🇹', date: '12/06 16h', group: 'Grupo B' },
  { id: 'm4',  home: 'Estados Unidos', homeFlag: '🇺🇸', away: 'Paraguai',      awayFlag: '🇵🇾', date: '12/06 22h', group: 'Grupo B' },
  { id: 'm5',  home: 'Austrália',     homeFlag: '🇦🇺', away: 'Turquia',        awayFlag: '🇹🇷', date: '13/06 01h', group: 'Grupo D' },
  { id: 'm6',  home: 'Catar',         homeFlag: '🇶🇦', away: 'Suíça',          awayFlag: '🇨🇭', date: '13/06 16h', group: 'Grupo E' },
  { id: 'm7',  home: 'Brasil',        homeFlag: '🇧🇷', away: 'Marrocos',       awayFlag: '🇲🇦', date: '13/06 19h', group: 'Grupo C' },
  { id: 'm8',  home: 'Haiti',         homeFlag: '🇭🇹', away: 'Escócia',        awayFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', date: '13/06 22h', group: 'Grupo C' },
  { id: 'm9',  home: 'Alemanha',      homeFlag: '🇩🇪', away: 'Curaçao',        awayFlag: '🏳️', date: '14/06 14h', group: 'Grupo F' },
  { id: 'm10', home: 'Holanda',       homeFlag: '🇳🇱', away: 'Japão',          awayFlag: '🇯🇵', date: '14/06 17h', group: 'Grupo G' },
  { id: 'm11', home: 'Costa do Marfim', homeFlag: '🇨🇮', away: 'Equador',     awayFlag: '🇪🇨', date: '14/06 20h', group: 'Grupo H' },
  { id: 'm12', home: 'Espanha',       homeFlag: '🇪🇸', away: 'Cabo Verde',     awayFlag: '🇨🇻', date: '15/06 13h', group: 'Grupo I' },
  { id: 'm13', home: 'Bélgica',       homeFlag: '🇧🇪', away: 'Egito',          awayFlag: '🇪🇬', date: '15/06 16h', group: 'Grupo J' },
  { id: 'm14', home: 'Arábia Saudita', homeFlag: '🇸🇦', away: 'Uruguai',      awayFlag: '🇺🇾', date: '15/06 19h', group: 'Grupo I' },
  { id: 'm15', home: 'Argentina',     homeFlag: '🇦🇷', away: 'Argélia',        awayFlag: '🇩🇿', date: '16/06 14h', group: 'Grupo K' },
  { id: 'm16', home: 'França',        homeFlag: '🇫🇷', away: 'Senegal',        awayFlag: '🇸🇳', date: '16/06 16h', group: 'Grupo I' },
  { id: 'm17', home: 'Portugal',      homeFlag: '🇵🇹', away: 'RD Congo',       awayFlag: '🇨🇩', date: '17/06 14h', group: 'Grupo L' },
  { id: 'm18', home: 'Inglaterra',    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', away: 'Croácia',      awayFlag: '🇭🇷', date: '17/06 17h', group: 'Grupo L' },
  { id: 'm19', home: 'Colômbia',      homeFlag: '🇨🇴', away: 'Uzbequistão',   awayFlag: '🇺🇿', date: '17/06 23h', group: 'Grupo K' },
  // 2ª Rodada
  { id: 'm20', home: 'Canadá',        homeFlag: '🇨🇦', away: 'Catar',          awayFlag: '🇶🇦', date: '18/06 19h', group: 'Grupo B' },
  { id: 'm21', home: 'México',        homeFlag: '🇲🇽', away: 'Coreia do Sul',  awayFlag: '🇰🇷', date: '18/06 22h', group: 'Grupo A' },
  { id: 'm22', home: 'Estados Unidos', homeFlag: '🇺🇸', away: 'Austrália',    awayFlag: '🇦🇺', date: '19/06 16h', group: 'Grupo D' },
  { id: 'm23', home: 'Escócia',       homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', away: 'Marrocos',     awayFlag: '🇲🇦', date: '19/06 19h', group: 'Grupo C' },
  { id: 'm24', home: 'Brasil',        homeFlag: '🇧🇷', away: 'Haiti',          awayFlag: '🇭🇹', date: '19/06 22h', group: 'Grupo C' },
  { id: 'm25', home: 'Alemanha',      homeFlag: '🇩🇪', away: 'Costa do Marfim', awayFlag: '🇨🇮', date: '20/06 17h', group: 'Grupo F' },
  { id: 'm26', home: 'Espanha',       homeFlag: '🇪🇸', away: 'Arábia Saudita', awayFlag: '🇸🇦', date: '21/06 13h', group: 'Grupo I' },
  { id: 'm27', home: 'Argentina',     homeFlag: '🇦🇷', away: 'Áustria',        awayFlag: '🇦🇹', date: '22/06 14h', group: 'Grupo K' },
  { id: 'm28', home: 'França',        homeFlag: '🇫🇷', away: 'Noruega',        awayFlag: '🇳🇴', date: '22/06 18h', group: 'Grupo I' },
  { id: 'm29', home: 'Portugal',      homeFlag: '🇵🇹', away: 'Uzbequistão',   awayFlag: '🇺🇿', date: '23/06 14h', group: 'Grupo L' },
  { id: 'm30', home: 'Inglaterra',    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', away: 'Gana',         awayFlag: '🇬🇭', date: '23/06 17h', group: 'Grupo L' },
  // 3ª Rodada
  { id: 'm31', home: 'Brasil',        homeFlag: '🇧🇷', away: 'Escócia',        awayFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', date: '24/06 22h', group: 'Grupo C' },
  { id: 'm32', home: 'Marrocos',      homeFlag: '🇲🇦', away: 'Haiti',          awayFlag: '🇭🇹', date: '24/06 22h', group: 'Grupo C' },
  { id: 'm33', home: 'Argentina',     homeFlag: '🇦🇷', away: 'Colômbia',       awayFlag: '🇨🇴', date: '26/06 22h', group: 'Grupo K' },
  { id: 'm34', home: 'França',        homeFlag: '🇫🇷', away: 'Espanha',        awayFlag: '🇪🇸', date: '27/06 22h', group: 'Grupos I' },
];
